site_name: Perceptrain
repo_url: "https://github.com/pasqal-io/perceptrain/"
site_url: "https://pasqal-io.github.io/perceptrain/"
repo_name: "perceptrain"

nav:
  - Home: index.md

  - Getting started:
    - Installation: getting_started/installation.md
    - Development & Info:
      - Contributing: getting_started/CONTRIBUTING.md
      - Code of conduct: getting_started/CODE_OF_CONDUCT.md
      - License: getting_started/LICENSE.md

  - Tutorials:
    - tutorials/index.md
    - ML Tools:
      - tutorials/qml/intro.md
      - Training: tutorials/qml/trainer.md
      - Data and Configurations: tutorials/qml/data_and_config.md
      - Training Callbacks: tutorials/qml/callbacks.md
      - Accelerator: tutorials/qml/accelerator_doc.md
      - CPU Training: tutorials/qml/CPU.md
      - GPU Training: tutorials/qml/GPU.md


  - API:
    - QML tools: api/ml_tools.md


  - Contact: https://github.com/pasqal-io/perceptrain/discussions

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/extras/overrides/
  logo: extras/assets/logo/perceptrain_logo_small_white.svg
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.copy
  - content.code.annotate

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    accent: custom
    toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: custom
    toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- footnotes
- pymdownx.arithmatex: # for mathjax
    generic: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: "!!python/name:markdown_exec.validator"
      format: "!!python/name:markdown_exec.formatter"

plugins:
- search
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          filters:
            - "!^_"  # exlude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods
            - "^__new__$"  # but always include __init__ modules and methods
        options:
          show_root_toc_entry: false
          heading_level: 3
          merge_init_into_class: true
          docstring_section_style: spacy

- markdown-exec

extra:
 version:
   provider: mike

# To get nice tabs
extra_css:
- extras/css/mkdocstrings.css
- extras/css/colors.css
- extras/css/home.css

# For mathjax
extra_javascript:
  - extras/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
- perceptrain
